In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

D:\Anaconda\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [5]:
df = pd.read_csv("10-diamonds.csv")

In [6]:
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  53940 non-null  int64
 1   carat       53940 non-null  float64
 2   cut         53940 non-null  str
 3   color       53940 non-null  str
 4   clarity     53940 non-null  str
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   price       53940 non-null  int64
 8   x           53940 non-null  float64
 9   y           53940 non-null  float64
 10  z           53940 non-null  float64
dtypes: float64(6), int64(2), str(3)
memory usage: 5.1 MB

In [4]:
df = df.drop("Unnamed: 0", axis=1)

In [5]:
df = df.drop(df[df["x"]==0].index)
df = df.drop(df[df["y"]==0].index)
df = df.drop(df[df["z"]==0].index)

In [6]:
df.describe()

,carat,depth,table,price,x,y,z
count,53920.000000,53920.000000,53920.000000,53920.000000,53920.000000,53920.000000,53920.000000
mean,0.797698,61.749514,57.456834,3930.993231,5.731627,5.734887,3.540046
std,0.473795,1.432331,2.234064,3987.280446,1.119423,1.140126,0.702530
min,0.200000,43.000000,43.000000,326.000000,3.730000,3.680000,1.070000
25%,0.400000,61.000000,56.000000,949.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5323.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [7]:
df = df[df["y"]<20]
df = df[df["z"]<10]
df = df[df["z"]>2]

In [8]:
df = df[df["carat"]<3.1]
df = df[(df["depth"]<75) & (df["depth"]>50)]
df = df[(df["table"]>48) & (df["table"]<72)]

In [9]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53887 rows x 10 columns]

In [10]:
X = df.drop("price", axis=1)
y = df["price"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [11]:
from sklearn.preprocessing import LabelEncoder

In [13]:
encoders = {}

for col in ["cut", "color", "clarity"]:
    encoders[col] = LabelEncoder()
    X_train[col] = encoders[col].fit_transform(X_train[col])
    X_test[col] = encoders[col].transform(X_test[col])

In [14]:
X_train

       carat  cut  color  clarity  depth  table     x     y     z
33066   0.32    2      4        1   61.2   57.0  4.41  4.44  2.71
14623   1.25    3      4        5   61.9   58.0  6.90  6.84  4.25
52671   0.52    2      0        4   61.3   56.0  5.21  5.22  3.20
32298   0.34    2      1        3   61.3   55.0  4.49  4.52  2.76
48726   0.52    2      3        7   61.0   56.0  5.24  5.18  3.18
...      ...  ...    ...      ...    ...    ...   ...   ...   ...
11293   1.00    4      4        5   60.7   60.0  6.55  6.49  3.96
44774   0.70    3      4        0   60.0   59.0  5.80  5.77  3.47
38199   0.50    2      2        3   61.6   57.0  5.14  5.08  3.15
860     0.90    3      6        2   62.8   59.0  6.13  6.03  3.82
15808   1.06    3      3        5   60.1   58.0  6.67  6.64  4.00

[37720 rows x 9 columns]

In [15]:
X_test

       carat  cut  color  clarity  depth  table     x     y     z
1812    0.78    4      1        2   60.9   57.0  5.93  5.97  3.62
49676   0.60    2      2        7   63.0   55.0  5.39  5.37  3.39
45705   0.56    2      3        5   62.1   56.0  5.31  5.29  3.29
14141   1.04    4      4        5   60.4   56.0  6.55  6.59  3.97
28636   0.33    4      6        4   62.8   58.0  4.38  4.41  2.76
...      ...  ...    ...      ...    ...    ...   ...   ...   ...
48329   0.34    3      4        3   58.6   62.0  4.62  4.60  2.70
36168   0.32    2      2        1   60.9   57.0  4.40  4.44  2.69
48687   0.77    1      1        3   64.1   56.0  5.84  5.77  3.72
33951   0.23    4      2        7   61.0   59.0  3.93  3.97  2.41
41004   0.55    2      2        3   61.7   55.0  5.26  5.28  3.25

[16167 rows x 9 columns]

In [19]:
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

In [20]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [21]:
svr = SVR(C=1000, gamma=0.1, kernel="rbf")
svr.fit(X_train_scaled, y_train)

SVR(C=1000, gamma=0.1)

In [ ]:
y_pred = svr.predict(X_test)
print("r2 score: ", r2_score(y_pred, y_test))

D:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but SVR was fitted without feature names
  warnings.warn(

In [1]:
print("r2 score: ", r2_score(y_pred, y_test))

NameError: name 'r2_score' is not defined

In [23]:
import pickle

In [24]:
with open ("diamonds_svr.pkl", "wb") as file:
    pickle.dump(
        {
            "model":svr,
            "encoder":encoders,
            "scaler":scaler
        },
        file
    )

In [25]:
pd.DataFrame(X_test_scaled).to_csv("30_testdatascaled.csv", index=False)